name: Java CI-CD

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  job1:
    name: Continous Integration
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
         java-version: '17'
         distribution: 'temurin'
         cache: maven
    - name: get the current path
      run: pwd
    - name: set initial path for building maven
      run: cd main\math-operations
    - name: Build with Maven
      run: mvn clean install
    - name: Run tests
      run: mvn test
      
  job2:
    name: Continous Delivery
    needs: job1
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploying to staging
        run: |
          echo "I have no staging environment, so just for practice... Completed"


